[build]
  command = "yarn run build"
  publish = "_site"

[context.production]
  command = "yarn run build"

  [context.production.environment]
    ELEVENTY_ENV = "production"
    NODE_ENV = "production"
    NODE_VERSION = "16"
    NETLIFY_USE_YARN = "true"

[[plugins]]
  package = "netlify-plugin-cache"

  [plugins.inputs]
    paths = [
      "_site/img/generated", # Eleventy image disk cache
      ".cache" # Remote asset cache
    ]

[[headers]]
  for = "/*"

  [headers.values]
    Content-Security-Policy = "script-src 'self'; style-src 'self' 'unsafe-inline'; object-src 'self'; img-src 'self' data: *.mapbox.com raw.githubusercontent.com kit.gaelryndel.xyz"
    Permissions-Policy = "interest-cohort=()"
    Referrer-Policy= "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*.ico"

  [headers.values]
    Content-Type = "image/x-icon"

[[headers]]
  for = "/*.json"

  [headers.values]
    Content-Type = "application/json; charset=utf-8"

[[headers]]
  for = "/*.webmanifest"

  [headers.values]
    Content-Type = "application/manifest+json; charset=utf-8"

# Netlify subdomain
[[redirects]]
  from = "https://gaelryndel.netlify.app/*"
  to = "https://gaelryndel.xyz/:splat"
  status = 301
  force = true

# www subdomain
[[redirects]]
  from = "https://www.gaelryndel.com/*"
  to = "https://gaelryndel.xyz/:splat"
  status = 301
  force = true

# 404s
[[redirects]]
  from = "*"
  to = "/404"
  status = 404

# Favicon
[[redirects]]
  from = "/favicon.ico"
  to = "/assets/icons/favicon.ico"
  status = 200
  force = true